stages:
  - test
  - build
  - publish

services:
    - docker:20.10.7-dind

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:latest

run-test:
  stage: test
  image: rust:latest
  script:
  - rustc --version && cargo --version
  - cargo test

build:
  stage: build
  image: rust:latest
  artifacts:
    paths:
      - dist/
  script:
  - rustc --version && cargo --version
  - rustup target add wasm32-unknown-unknown
  - cargo install trunk
  - trunk build --release

docker:
  stage: publish
  image: docker:18.09-dind
  needs:
    - build
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
